version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  unms-data:
  nginx-data:
  letsencrypt:
  config:
    driver: local
  log:
    driver: local
  log2:
    driver: local
  run:
    driver: local
  run2:
    driver: local
  work:
    driver: local

services:
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  unbound:
    build: ./unbound
    ports:
      - '1053:53/tcp'
      - '1053:53/udp'
  ddclient:
    build: ./ddclient-cloudflare
    privileged: true
  nginx:
    build: ./nginx
    privileged: true
    ports:
        - "443:443"
    volumes:
        - "nginx-data:/app/data"
        - "letsencrypt:/etc/letsencrypt"
    links:
        - "unifi"
        - "unms"
  unifi:
    image: ryansch/unifi-rpi:latest
    restart: always
    network_mode: host
    ports:
        # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
        - "10001:10001/udp" # AP discovery 
        - "3478:3478/udp" # STUN
        - "6789:6789" # Mobile speed tests
        - "8080:8080" # Device controller communication
    volumes:
        # Unifi v5.0.7 creates all of these directories (some remain empty)
        - config:/var/lib/unifi
        - log:/usr/lib/unifi/logs
        - log2:/var/log/unifi
        - run:/usr/lib/unifi/run
        - run2:/run/unifi
        - work:/usr/lib/unifi/work
  unms:
    image: oznu/unms:armhf
    volumes:
        - "unms-data:/config"
  
