version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  unms-data:
  nginx-data:
  letsencrypt:
  unifi-config:
    driver: local
  unifi-log:
    driver: local
  unifi-log2:
    driver: local
  unifi-run:
    driver: local
  unifi-run2:
    driver: local
  unifi-work:
    driver: local
  
services:
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    restart: unless-stopped
    network_mode: host
  unbound:
    build: ./unbound
    ports:
      - '1053:53/tcp'
      - '1053:53/udp'
  ddclient:
    build: ./ddclient-cloudflare
    privileged: true
  nginx:
    build: ./nginx
    privileged: true
    ports:
        - "443:443"
    volumes:
        - "nginx-data:/app/data"
        - "letsencrypt:/etc/letsencrypt"
    links:
        - "unifi"
        - "unms"
  unifi:
    image: ryansch/unifi-rpi:5.10.19-arm32v7
    ports:
        - "3478:3478/udp"
        - "6789:6789"
        - "8080-8081:8080-8081"
        - "8443:8443"
        - "8843:8843"
        - "8880:8880"
        - "10001:10001/udp"
    container_name: unifi
    volumes:
        - unifi-config:/var/lib/unifi
        - unifi-log:/usr/lib/unifi/logs
        - unifi-log2:/var/log/unifi
        - unifi-run:/usr/lib/unifi/run
        - unifi-run2:/run/unifi
        - unifi-work:/usr/lib/unifi/work
    restart: unless-stopped
  unms:
    image: oznu/unms:armhf
    volumes:
        - "unms-data:/config"
    restart: unless-stopped
    ports:
      - "9001:443"
  
